sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-010
env:
  global:
    -
      # LTD_AWS_ID
      secure: dXDgyk5JsvStzWkR7DZkF2Mv3FVeUBvmQprXFXzhTX9QXxn+oBFoBgp80bTWy4V6opvQ9wgkW/z/qjCJCboouuuTgCa6isc67xi4TLEtWunC152c9AJxw08Vca5xUQMy1g75TDblhPRnP1m5yFoOx3s8ptLLoPK6VzlaCH+GGvAEol1bXSQve5v4iMXMlk/SCXD2wDxe73ouvl5dCVbLd+QjSNxLn/70lSpU8QOSf3sozdb8ZZg969vSg9yGA7QXsSjU9D4JWBGL1Vl68aLyDeNYBG4t93lO8oAmQoSfBIoL3Rlg7I/Puh/s0wNJ+p5xoIl5VvxxT5uW1srAbsnr7We0NZfJ8FtqKWQUN0YHjY4uglJJbTSHXCOYTHrUSBJA1MgXFshI1XKvAWxrH4Fn4CbBhrKDZQk+4lzzH/Rnpf69dbwLUNbqr2JsoRxAs0uSzkXOEZzPc6xYJahENKTVOT2fZ35qDWwx8nKaeKIhHcjiqDedCFAcnV/Nyt+udfaESkxVWkO+WMCRVOTIg4Py4rqnBGy9rM4ar9KmOImmQ4iDIQ1JnnRiZi6/nMVqV3Dm6h19TmYve88Oe6GrZ4g0SYbtMUWOPk8VdjmBoNeAUEQTbzaclUPO+edG0M/RiOZrKmJ7llzKyXu/Ew04oVV50jfwVu+FXvCrUw0rcu1M5o8=
    -
      # LTD_AWS_SECRET
      secure: hPpnqpQ2qUV0zMe53Iq5GS4QrYyks5x3xTJHiUmjOyqo6QvuBhZEwi4UHCKyfCIanI4LCnGudFhk2ezrgAFryaHd6Ea7zoWQ5y1NJ67nL2Bmci6p266Q2w1C2okqVJZ2WYOG6AgiScfAQYaSa5aID7LqhT+DnXcrzWh+9EZ9cQho9iUUDSMdJtkVyS+rVFAg4ss/7mkbuETUQhS8oYDJKF5g+fsI06l5txXT3Hj0WSugklNhZmpBAgj73U4DnUHjx5a9+5+tvahypLKISmiuZkcOr6R7s9FGocdRSZHqIEzohmQj0L1njx4SKQQsbwAEK7w/Fhw6SHi8xzTCTVDtrBk2W6lrvRt8TFl3Djy+tNGrtFyBBQT9kQFuFPPeaP0Z5ajUvSoAfF9eChvN/k6rGi1opSQdBwjlRvO5V6tVBP7uuAcVcRg0gX/NElOIovNsJAOdMbkmUxiYIJm44Mh9cVCksSiP94uOJyc+pQPzMMrxABKgsqNBkn6vonlLNhutJdcTq/6QjyMZCGB/y9NEvLVunIvJRio8SwM7UZTewEbTkFntktNYE1Um9pC4mfJLn9odQxHuf4h4XaKKP/b26cGJmvTTVMrLxyTavNNTRA4U8WAaHbusqPoD1flUJiq4zd6bT6MCjhBObpl0seOeh8k/qkgLf4pL/JiP++Oh3o8=
    -
      # LTD_USERNAME
      secure: Ob2+FNvUzn8uL9gw8jS3GPqZeFXGw+zunlWAmPmjD0geOvIGVwbjuttBeSXQlYGofaMsW1tNkNHM+sv0WRZokkb86mv/l/J0/BWOAAmP83bEJ6TkQ6+EQvU4WyLld2t+Qt1yaguArMLQTuUlZ4Fmkq0HwPcq/H+E57Ge1cabxjvddPelpsmE+3XNP4QDok5o4fuFnFF4LOsKvPG4ats1qrJQEtt9sd19RZz1VOARByVKTIKd1x4IV7RBnFDzUi7NUuLYI/6Ou/WsqHvx0SNjBR+86ljVPf9Jmo+LeSPS+do34LIlHWd4/NmaYZf9KxzpL1t+0VG4+P63F+7ZuizzNTepiWiBDrEBToiXoQ9DP50xZj9DeXU4Ao6EN3b6UqdYdBHmY/crJEEPhB7W63vNx3wrFKACqIQV2yEt61MypigUcubvc5r7+j/ADSP+sxEGxVn6vIooVmpBuZqnH7TmbpxP+T0hxitw/cNPx5Gqq6kHNEuUTSq8wEhRlvkJkJu37a+T8sJcO+ndOriYQKu03WaQpvnw+RBdryxajrDjt3ukD+9pMugyxN7L2UdFea+0etp1aVWvVD+VNo4N7COH4WDQDQyamHCKHkKw1mCnBk3fTkmxjQ48Op49Tja/1CLRZjRUMRXYuN32Uzbq5TwiGBi0fDJmfXzwMhvk/8CdkjY=
    -
      # LTD_PASSWORD
      secure: RJPAvMWf5bXzvNkOCKYgBI7/Z9usSRDWEFMa9ZAz/UTHN+yBAJd6jmlf3dFJcGWdvykzS8jG7P0LZhWShodABd/4Mgm+TuE1sxUK2KVom8PI68RfGCSK2lx6EzgbkNwwyCeY4BAEp3QjY/1wvRKyhIqejVNqsPtQJzUnmFFBCwAhS1Tc5BrPxD1KGIh0uCAGCBsW5xnlqi8B1BuM9sRWWdg4dIaCg9FR2BZsBElkxtRE5SQ6spr1DN/LkDUiMjABygGve49H6NyYiAAGYey8uOAJq4Jj0B0gyg+3b01xBLtb3JwYyn6/sVuanqc+M4MEOFn3NwwawmiBjEAAc+2l63dgsTPlbX+kGdhaG1p6IalkEZQZ/vcG4dtl9k167Jb8Zjm5IBXRgG1wjD8dils0gsq9oWo2FQDA8MBRT8z7DYU5kwl9f6XfaceaY2fdcRIO9wGlvm1O+kqjDZ14WXdKdYNn0aJ7Um5AvYFwPALI8vokXEcWJ3RObbqY9JmX5b69z7ndJjA5UBu63uRssWjxatvVV3IwOZPjP0cPP47QfR26zVH9c+pFDObyock7MNl+Hu3gQSnKcVSyb5W5YrI2l9s6c2fxWpD+cDry5suHhXnG0JkzMsHwSzat5TgoGwPgtr+dTJRMKqYq+yKES3H+7Vk8vN2ZK+AIFWwDNWVg0wc=
